### ISSUE TITLE
Error running monero-lws-admin with `--network test`: "No such command"

### ISSUE THREAD

**Issue by woodser** [vtnerd/monero-lws#107]
Running the `monero-lws-admin` with `--network test` gives an error:

```
./monero-lws-admin --network test create_admin
No such command
```

Using `main` or `stage` gives an error about genesis mismatch as expected.

**Comment by vtnerd** [comment]
Is this the release branch? The create_admin command is not supposed to be on that branch. At some point I will create a 0.3 release branch with that feature

**Comment by woodser** [comment]
Yeah it's the release branch. My tests are all based on the release branch of monero-project, so I may not be able to run the light wallet server in the meantime.

**Comment by vtnerd** [comment]
I'm working on a 0.3 release - there's one other person that could use it. I'm just slowly deciding what features will go on that branch now.
