### ISSUE TITLE
failed to decrypt amount for tx

### ISSUE THREAD

**Issue by dzonatan** [vtnerd/monero-lws#11]
Decrypting the incoming transaction seems not be working. In the logs I'm getting a warning:
```
<time> W <base58 address> failed to decrypt amount for tx <tx id>, skipping output
```
Initiating the `rescan` through admin doesn't help either - the same warning occurs again.

What could have cause this?

FIY: Using main network, monero dependency was built from v0.17 branch, everything according to the readme.

EDIT: I think that might be related to unsupported CLSAG format as I can't find anything within sources.

**Comment by vtnerd** [comment]
This [change](https://github.com/vtnerd/monero-lws/commit/f077953e02941e8e931a5f7aa870ced3b72a1f1e) should fix it.

**Comment by dzonatan** [comment]
It did help! Thanks, again! 🍻
