### ISSUE TITLE
Didn't work for wownero

### ISSUE THREAD

**Issue by MyatLinn3** [vtnerd/monero-lws#115]
Hey 
Thanks for the project, If one want use wownero node what are the steps?

**Comment by vtnerd** [comment]
I'm not going to give much advice for wownero, but the most glaring issue is the [prefix for addresses](https://github.com/vtnerd/monero-lws/blob/master/src/db/string.cpp#L43C24-L43C50) needs to change. There might be a few other small things I'm not thinking about right now.

**Comment by vtnerd** [comment]
There's also this [checkpoint code](https://github.com/vtnerd/monero-lws/blob/master/src/db/storage.cpp#L434) that needs to be changed.
