### ISSUE TITLE
If you try to create more accounts, HTTP 500 error will be returned  

### ISSUE THREAD

**Issue by serhack** [vtnerd/monero-lws#14]
[Lightwallet API description](https://github.com/monero-project/meta/blob/master/api/lightwallet_rest.md) describes the following behaviour at paragraph about "login" request:

> If approval process is manual, a successful HTTP 200 OK and response object must be returned. Subsequent requests shall be HTTP 403 "Forbidden" until account is approved.

Instead, the server returns 500 error at calling `/login` with the same request.

**Comment by vtnerd** [comment]
Fixed with PR #20
