### ISSUE TITLE
Genesis hash mismatch while running testnet daemon

### ISSUE THREAD

**Issue by edgzoah** [vtnerd/monero-lws#147]
Hi, i'm trying to run the monero-lws-daemon unfortunetly i got error:

`./monero-lws-daemon --network=test`
`E Genesis hash mismatch (thrown at storage.cpp:482): Unable to sync blockchain - wrong --network ?`

monero testnet daemon is running on 127.0.0.1:28081

**Comment by vtnerd** [comment]
Is the `monerod` instance also running testnet? You need to start the daemon with the `--testnet` flag. This code hasn't changed, so should be related to that.

**Comment by vtnerd** [comment]
Could you provide the command you used to start `monerod`?

**Comment by vtnerd** [comment]
Nevermind, I know what the error is.

LWS doesn't create database files for different network type, so you must remove the DB file or use `--db-path`.  A previous run of `monero-lws-daemon` created the database file and synced and initialized to mainnet.
