### ISSUE TITLE
"Serious database error, no receive for spend"

### ISSUE THREAD

**Issue by serhack** [vtnerd/monero-lws#15]
If you try to scan for transactions, starting from scratch, on stagenet, the daemon of lightwalletserver will throw the following error:
`Exception at [connection<t_protocol_handler>::handle_read], what=Serious database error, no receive for spend` 

If you're curious, you can see the logical error [from source](https://github.com/vtnerd/monero-lws/blob/develop/src/rest_server.cpp#L298). 

I tried to open and create three different wallets on lightwalletserver that were created by community members to play around with.  

### Steps to reproduce
1. Add a new account 
2. Start the scanning from scratch (height 0)
3. Wait

### Details
Ubuntu 20 LTS and latest version of LWS from `develop` branch.

**Comment by vtnerd** [comment]
There were more steps than this required to reproduce, but I should have this fixed. Check latest code in `develop` branch. Make sure the balance is computed correctly.

**Comment by vtnerd** [comment]
Also, no rescans or any DB related changes should be necessary. Just fetch code, compile, then check json response.

**Comment by vtnerd** [comment]
Was this issue resolved?

**Comment by serhack** [comment]
Yep, forgot to update you. Confirmed to be fixed, tested using stagenet and 0.17.2.
