### ISSUE TITLE
Impossible to send Monero: Key "relayed" missing from object.

### ISSUE THREAD

**Issue by serhack** [vtnerd/monero-lws#16]
I'm still testing lightwallet server daemon and via a workaround (yes, now it's totally a workaround, aka commenting the error) for #15 issue, I tried to send some Monero to another address from stagenet. I'm using OpenMonero frontend with a custom configuration.

The problem is that when daemon receives the transaction from the call `submit_raw_tx`, the following error appeared:
` E Exception at [connection<t_protocol_handler>::handle_read], what=Key "relayed" missing from object.`

**Comment by vtnerd** [comment]
The daemon is returning an error response that wasn't being properly handled. The latest version should provide the error message that the server was sending. The daemon logs may also have the issue.

Most likely its a double-spend due to the other issue you are having.

**Comment by serhack** [comment]
`Server returned RPC error: invalid output with code 1 called from rest_server.cpp:643` 

At least now API throws an error! Last time, the call went into timeout and it was not possible to see if the action was performed successfully from the frontend.

**Comment by vtnerd** [comment]
This is likely an issue on the wallet side. Run `set_log 2` on the daemon to get some detailed info on why the daemon is rejecting it. There will be lots of stuff spammed to console, so look for an error involving an output. Most likely the wallet you are using has not been upgraded to create CLSAG outputs, which `monero-lws` can't resolve.

**Comment by vtnerd** [comment]
Is this resolved?

**Comment by vtnerd** [comment]
I think this was resolved, if not ping to re-open.
