### ISSUE TITLE
Build error HIDAPI_LIBRARY

### ISSUE THREAD

**Issue by trasherdk** [vtnerd/monero-lws#3]
In Monero dependencies libhidapi is an optional dependency, and I don't have it.

It's not listed as a dependency for this thing.

Could it be detected by cmake, and not used if not available?

```
[ 93%] Linking CXX executable monero-lws-daemon
/usr/lib64/gcc/x86_64-slackware-linux/5.5.0/../../../../x86_64-slackware-linux/bin/ld: cannot find -lHIDAPI_LIBRARY-NOTFOUND
```

**Comment by TheCharlatan** [comment]
I voiced this before, but I hate that hardware wallet stuff bleeds into purely server side code.

**Comment by vtnerd** [comment]
The dependency should only be needed if the Monero was built with it. This is unavoidable currently, since several of the core Monero components depends on the `device` folder internally. The fix is to match against `HIDAPI_LIBRARY-NOTFOUND` and setting the corresponding string to `""` when true.

**Comment by trasherdk** [comment]
Well. Monero builds, and runs, just fine without a hidapi library installed, but is required by monero-lws.

I have build a install package of hidapi for my system, so it's not a problem for me anymore.

Maybe "someone" could put in that HIDAPI_LIBRARY-NOTFOUND fix in. I'm not too muck into CMake to do it my self.

**Comment by vtnerd** [comment]
Commit e2a00f6b60d9a9f7edaa2ffad82298a639cddd79 should fix this.
