### ISSUE TITLE
Version control & What Monero-LWS branch to build on for stability?

### ISSUE THREAD

**Issue by shermand100** [vtnerd/monero-lws#34]
Hi, whilst building Monero-LWS I got the error:

> [ 39%] Building CXX object src/db/CMakeFiles/monero-lws-db.dir/data.cpp.o
> In file included from /home/pinodexmr/monero-lws/src/db/data.cpp:32:
> /home/pinodexmr/monero-lws/src/./wire/crypto.h:74:26: error: ‘view_tag’ is not a member of ‘crypto’
>    74 |   struct is_blob<crypto::view_tag>
>       |                          ^~~~~~~~
> /home/pinodexmr/monero-lws/src/./wire/crypto.h:74:26: error: ‘view_tag’ is not a member of ‘crypto’
> /home/pinodexmr/monero-lws/src/./wire/crypto.h:74:34: error: template argument 1 is invalid
>    74 |   struct is_blob<crypto::view_tag>
>       |                                  ^
> make[2]: *** [src/db/CMakeFiles/monero-lws-db.dir/build.make:90: src/db/CMakeFiles/monero-lws-db.dir/data.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:276: src/db/CMakeFiles/monero-lws-db.dir/all] Error 2
> make: *** [Makefile:136: all] Error 2

Which with a bit of digging is just the set-up for the next Monero hard-fork so I expect that error will disappear after the update when  references to Moneros crypto.h line-up, but it led me to ask:

Your build instructions on this github frontpage say to use `git checkout develop` to build Monero-LWS which is currently not working.

I'd like to implement Monero-LWS into my project PiNodeXMR so have the install process scripted in. If I instead scripted in the branch  `git checkout release-v0.1_0.17` (which builds correctly) Is this likely to be stable for people to use short term?

Then could I expect a future stable branch after the hard fork to reference instead of 'develop' which may continue to intermittently have these sorts of issues?

**Comment by selsta** [comment]
Support for view tags got added recently: https://github.com/vtnerd/monero-lws/pull/33

ping @j-berman

**Comment by j-berman** [comment]
> If I instead scripted in the branch git checkout release-v0.1_0.17 (which builds correctly) Is this likely to be stable for people to use short term?

This will work for the short term. Keep in mind you'll need to update again for the upcoming hard fork.

At this exact moment:

`monero-lws/develop` (https://github.com/vtnerd/monero-lws/commit/5081062c7c65fab68b75da8d6819bdc3c63666c5) builds with `monerod/master` (https://github.com/monero-project/monero/commit/9750e1fa103539b3e533455500610aae76e253a5)
`monero-lws/master` (https://github.com/vtnerd/monero-lws/commit/dbbdee6fd4ba81125a9454d7dbecbff5d4196368) builds with `monerod/release-v0.17` (https://github.com/monero-project/monero/commit/424e4de16b98506170db7b0d7d87a79ccf541744)
`monero-lws/release-v0.1_0.17` (https://github.com/vtnerd/monero-lws/commit/f009e768744abad5ee2343aaa5c54ee0d7cf6bb1) builds with `monerod/release-v0.17` (https://github.com/monero-project/monero/commit/424e4de16b98506170db7b0d7d87a79ccf541744)

My opinion on a longer run approach:

`monero-lws` introduces a more formal release process with tagged versioned releases that explicitly build with particular `monerod` versions, released using github's release system along with signed binaries for different platforms.

In the `monero-lws` README, the build instructions could suggest to build `monerod` at a particular version (e.g. v0.17.3.0). The master branch in `monero-lws` should be expected to build with that version of `monerod`. The master branch should also be the default branch when checking out the repo.

The `develop` branch could be used for development and shouldn't be expected to be stable, and shouldn't be included as the default build suggestion in the README (except for contributors).

Above seems most intuitive to me and ensures that `monero-lws` always builds as expected when people visit the repo.

**Comment by vtnerd** [comment]
@j-berman I recall wanting it to be this way (as per master->master anyway), so I'm not sure how this happened, other than it being an oversight. I think the future master->master builds should just work, which could be annoying for merging in features, but I don't see another way (until when/if the monero core is provided in a better library system).

**Comment by vtnerd** [comment]
Nope I see what happened, that epee util change probably broke master->master stuff.

**Comment by j-berman** [comment]
Seems like I should have submitted #33 against master instead of develop then?

**Comment by shermand100** [comment]
So I'll for now use the Monero-LWS branch "release-v0.1_0.17" against Monero 0.17.3.2 for now and not expect changes that may break it? (I build monero with monero/release-v0.17 so that makes sense)

Then re-visit this after the hard fork.

**Comment by vtnerd** [comment]
@j-berman I will just cherry pick the relevant change instead.

**Comment by vtnerd** [comment]
@shermand100 Yes, and many people should probably be doing that anyway because `master` was only intended to work with the `master` branch on Monero.

**Comment by vtnerd** [comment]
All branches should be build now (less some distro related issues).
