### ISSUE TITLE
Dockerfile v0.2 fails to build (libunbound static link)

### ISSUE THREAD

**Issue by vdo** [vtnerd/monero-lws#38]
Running `docker build -t monero-lws:v0.2_0.18 . --no-cache` on [v0.2_0.18]( https://github.com/vtnerd/monero-lws/tree/release-v0.2_0.18) fails when linking with `libunbound`:
https://paste.sethforprivacy.com/?632a27d7e6e7208d#GzoXnKzpwcQrdvnwRk2ir2wKPmcwtZhHvnpRpsWgou7U

**Comment by vtnerd** [comment]
See PR #39

**Comment by vtnerd** [comment]
Should be fixed now.
