### ISSUE TITLE
 Status:404Not Found

### ISSUE THREAD

**Issue by abdevil05** [vtnerd/monero-lws#50]
Title - Status:404Not Found

Description-when i try to hit login endpoint with postman,its shows  Status:404Not Found and in terminal i got the error which has the screeeenshot that is attached below.

what changes do i need to do in the lws git hub to get the correct output.

The correct output should be-:
{
"new_address":0
"generated_locally":1
}

![Screenshot from 2022-09-13 12-42-29](https://user-images.githubusercontent.com/109150628/189848099-1aba2e4b-3ef7-49a2-b31b-e29d1e579b52.png)

**Comment by vtnerd** [comment]
I think the issue might be SSL - the server is likely expecting no SSL, but the command is being sent with it. That's my best guess because the first line says "failed to match first line", which is indicating that the HTTP client message was invalid somehow.

**Comment by vtnerd** [comment]
Again, closing as stale due to no follow up.
