### ISSUE TITLE
After version update node to 0.18 and lws to 0.2_0.18: No active accounts

### ISSUE THREAD

**Issue by Frazer-dl** [vtnerd/monero-lws#51]
After update I get this messages. 
20.09.2022 10:50:512022-09-20 07:50:51.816	I Starting blockchain sync with daemon
20.09.2022 10:50:512022-09-20 07:50:51.817	I Retrieving current active account list
20.09.2022 10:50:512022-09-20 07:50:51.818	I No active accounts
But the account (pubkey, view key) was added using monero-lws-admin

I'll be glad to hear your suggestions :)
Maybe I miss something..

**Comment by vtnerd** [comment]
Sorry for the delay - install the application `jq` which helps with filtering some stuff. I'm not suggesting that you post the responses to these commands - sensitive information may be in it - however it will help determine the database state.

The command: `monero-lws-admin list_accounts | jq -r '.active | .[] | .address'` will list every account that is active. This should be an empty list. I would also just run `monero-lws-admin list_account` to see if there are any accounts listed in _other_ states (than `active`).

There's also the `monero-lws-admin debug_database` command, but I don't think that's necessary (at least not yet).

**Comment by cuterrrrrrrrrrr** [comment]
Do you address this? I suffer from it too.

**Comment by Frazer-dl** [comment]
> Do you address this? I suffer from it too.

Yeah, just add account and start rescan for it
