### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by victor-tucci** [vtnerd/monero-lws#55]
[ 84%] Linking CXX executable monero-lws-admin
**Undefined symbols for architecture arm64:**
  "_IOPSGetTimeRemainingEstimate", referenced from:
      cryptonote::miner::background_worker_thread() in libcryptonote_basic.a(miner.cpp.o)
      cryptonote::miner::on_battery_power() in libcryptonote_basic.a(miner.cpp.o)
**ld: symbol(s) not found for architecture arm64**

**Comment by victor-tucci** [comment]
can someone help me to fix the issue. i am try to build in mac M2 chip

**Comment by selsta** [comment]
Which branch are you building? This should be solved by https://github.com/vtnerd/monero-lws/pull/46

**Comment by victor-tucci** [comment]
i tried master branch

**Comment by victor-tucci** [comment]
but if i try to build the develop branch i am facing the error of 

In file included from /opt/homebrew/include/boost/asio/ssl/context.hpp:23:
In file included from /opt/homebrew/include/boost/asio/ssl/context_base.hpp:19:
/opt/homebrew/include/boost/asio/ssl/detail/openssl_types.hpp:23:10: fatal error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^~~~~~~~~~~~~~~~
1 error generated

**Comment by vtnerd** [comment]
@selsta I haven't cherry-picked this onto other branches yet. It only exists in `develop`. The change is simple enough that I will immediately cherry-pick onto `master` (without PR/review, it should work unchanged afaik).

**Comment by vtnerd** [comment]
@victor-tucci do you have any more from the error with the `master` branch? And what version of boost is this? I assume the source of the error is from something in `epee` that includes `boost::asio::ssl`, which then propagates further errors.

**Comment by vtnerd** [comment]
@victor-tucci  - the patch @selsta mentioned has been cherry-picked onto the `master` and `release-v0.2_0.18` branches. If you are still having trouble, you may want to try them.

**Comment by victor-tucci** [comment]
yes I tried with that #46 it's work now @vtnerd  @selsta
