### ISSUE TITLE
Monero-Lws can't catch request parameters with `wire::json`

### ISSUE THREAD

**Issue by lovelyrrg51** [vtnerd/monero-lws#57]
After running monero-lws, when try to call apis, can't catch request parameters.
As a result of track, can't change string to json in `wire::json`.
Is there anyone to help?
Thanks.
![image](https://user-images.githubusercontent.com/56916797/202804139-3e259e71-5b6d-4ebd-b13a-6a1b69171786.png)

**Comment by vtnerd** [comment]
I don't follow exactly. There is some field missing according to the log statement. Is there a required field that you feel should be optional?

**Comment by vtnerd** [comment]
There's been no follow up, so closing this issue for now.
