### ISSUE TITLE
get_address_tx discrepancies between LWS and api.mymonero.com

### ISSUE THREAD

**Issue by CryptoGrampy** [vtnerd/monero-lws#69]
I notice 2 discrepancies between LWS and api.mymonero.com API responses to the get_address_tx call after making the first spend from a fresh wallet.  

1. MyMonero API sends a "fee" property with the fee amount in a string in one of the transactions in the transaction array (the one that contains a value for total_sent.

2. MyMonero API does not include the ```spent_outputs``` property on transactions in the transaction array when the array is empty. 

Example response from api.mymonero.com for the transactions array:

```json
"transactions": [
    {
      "hash": "xxxx",
      "id": xxxxx,
      "timestamp": "xxxxx",
      "total_received": "1000000000",
      "total_sent": "0",
      "unlock_time": 0,
      "height": xxxxx,
      "coinbase": false,
      "mempool": false,
      "mixin": 15,
      "payment_id": "xxxxx"
    },
{
      "hash": "xxxx",
      "id": xxxxxxx,
      "timestamp": "xxxxxx",
      "total_received": "942420000",
      "total_sent": "1000000000",
      "fee": "47580000",
      "unlock_time": 0,
      "height": xxxxxx,
      "coinbase": false,
      "mempool": false,
      "mixin": 15,
      "payment_id": "xxxxxx",
      "spent_outputs": [
        {
          "tx_pub_key": "xxxxxx",
          "key_image": "xxxx",
          "amount": "1000000000",
          "out_index": 1,
          "mixin": 15
        }
      ]
    }
    ]
```

LWS get_address_tx response for transactions array:

```json
"transactions": [
    {
      "id": 0,
      "hash": "xxxxx",
      "timestamp": "xxxxx",
      "total_received": "1000000000",
      "total_sent": "0",
      "unlock_time": 0,
      "height": xxxxx,
      "payment_id": "xxxxx",
      "coinbase": false,
      "mempool": false,
      "mixin": 15,
      "spent_outputs": []
    },
    {
      "id": 1,
      "hash": "xxxxx",
      "timestamp": "2023-04-22",
      "total_received": "942420000",
      "total_sent": "1000000000",
      "unlock_time": 0,
      "height": 2869584,
      "payment_id": "xxxxx",
      "coinbase": false,
      "mempool": false,
      "mixin": 15,
      "spent_outputs": [
        {
          "amount": "1000000000",
          "key_image": "xxxxx",
          "tx_pub_key": "xxxxx",
          "out_index": 1,
          "mixin": 15
        }
      ]
    }
  ]
```

I think the result of these (and there are likely more) discrepancies is a lot of bugginess (transaction calculation issues in particular) when trying to use the MyMonero wallets and libraries (MyMonero-utils) with LWS.   I haven't looked closely at the LWS API spec, but from an end user and community standpoint, there are basically zero out of the box options out there for consuming the open source LWS server, so I would probably recommend updating this library to match MyMonero.

**Comment by vtnerd** [comment]
#74 adds the fee and #70 truncates arrays when the length is zero.

**Comment by vtnerd** [comment]
I have unit tests to verify that the arrays are omitted, so I think this can be closed.
