### ISSUE TITLE
Get_address_info don`t give any information

### ISSUE THREAD

**Issue by MrsPiano** [vtnerd/monero-lws#9]
I start the daemon by 
`monero-lws-daemon --rest-server http://0.0.0.0:8443 --confirm-external-bind`

Send request to http://*********:8443/login      
With data:
`{"address":"MY ADDRESS","view_key" => "MY PRIVATE VIEW KEY","create_account" => true,"generated_locally" => false}`

And get good answer, from server

Then i make second request to http://*********:8443/get_address_info
With data:

`{"address":"MY ADDRESS","view_key" => "MY PRIVATE VIEW KEY"}`

And get answer in ssh that **No account with the specified address exists from**

What`s wrong? Thx

**Comment by vtnerd** [comment]
You already closed this, so presumable you fixed it. Most likely the issue was an unapproved viewkey ?
